name: Tests

on:
  push:
    branches-ignore:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.4
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm lint
      - run: pnpm lint:ts
      - run: pnpm build
